In [1]:
import tensorflow as tf
tf.__version__

'1.14.0'

In [0]:
# Creates a constant op
# This op is added as  anode to the default graph

hello = tf.constant('Hello, TensorFlow!')

In [0]:
# Start a TF Session
sess = tf.Session()

In [4]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [5]:
# To run and op and get the result
sess.run(hello)

b'Hello, TensorFlow!'

In [7]:
result = sess.run(hello)
type(result)

bytes

In [8]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [9]:
type(sess)

tensorflow.python.client.session.Session

In [0]:
?tf.constant

### Computational Graph

In [0]:
# node1 = tf.constant(3.0, tf.float32)

node1 = tf.constant(3.0)
node2 = tf.constant(4.0)
node3 = tf.add(node1, node2)

In [12]:
print('node1:', node1)
print('node2:', node2)
print('node3:', node3)

node1: Tensor("Const_1:0", shape=(), dtype=float32)
node2: Tensor("Const_2:0", shape=(), dtype=float32)
node3: Tensor("Add:0", shape=(), dtype=float32)


In [13]:
sess = tf.Session()
print('sess.run(node1, node2)\t: ', sess.run([node1, node2]))
print('sess.run(adder_node) \t:', sess.run(node3))

sess.run(node1, node2)	:  [3.0, 4.0]
sess.run(adder_node) 	: 7.0


In [14]:
type(node3)

tensorflow.python.framework.ops.Tensor

In [15]:
type(sess.run(node3))

numpy.float32

### TensorFlow Mechanics
#### Placeholder

In [0]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

# + provides a shortcut for tf.add(a,b)
adder_node = a+b

In [19]:
sess.run(adder_node, feed_dict={a:3, b:4.5})

7.5

In [20]:
sess.run(adder_node, feed_dict={a:[1,3], b:[2,4]})

array([3., 7.], dtype=float32)

In [0]:
add_and_triple = adder_node*3

In [23]:
sess.run(add_and_triple, feed_dict={a:3, b:4.5})

22.5

In [24]:
import tensorflow as tf

# 변수 a, b 는 동적으로 지정
# a = tf.placeholder('float32')
# b = tf.placeholder('float32')

a = tf.placeholder('int32')
b = tf.placeholder('int32')

# multipy함수는 입력된 정수 a, b의 곱셈을 반환
# y = tf.mul(a, b)

y = tf.multiply(a,b)

sess = tf.Session()

print('tf.mul({a}, {b}) : {y}'. format(a=20, b=30,
                                      y=sess.run(y, feed_dict={a:20, b:30})))

tf.mul(20, 30) : 600


### Constant & Variable

In [28]:
import tensorflow as tf

x = tf.constant(100, name = 'x')
y = tf.Variable(x*2, name = 'y')

# model = tf.global_variables_initializer()

model = tf.initialize_all_variables()

with tf.Session() as sess:
  sess.run(model)
  print('Check the variable: \n - constant x: {x} \n- Variable y : {y}'.format(
  x = sess.run(x),
  y = sess.run(y)))

Instructions for updating:
Use `tf.global_variables_initializer` instead.
Check the variable: 
 - constant x: 100 
- Variable y : 200


Tensorflow 연산

In [0]:
import numpy as np

In [30]:
tensor_1d = np.array([1.2, 3.4, 5.6, 7.8])
tensor_1d

array([1.2, 3.4, 5.6, 7.8])

In [31]:
tensor_2d = np.arange(16).reshape((4,4))
tensor_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [0]:
sess = tf.Session()
tf_tensor_1d = tf.convert_to_tensor(tensor_1d, dtype=tf.float64)
tf_tensor_2d = tf.convert_to_tensor(tensor_2d, dtype=tf.float64)

In [33]:
sess.run(tf_tensor_1d)

array([1.2, 3.4, 5.6, 7.8])

In [34]:
sess.run(tf_tensor_2d)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [35]:
sess.run(tf_tensor_1d[0])

1.2

In [36]:
sess.run(tf_tensor_1d[2:])

array([5.6, 7.8])

In [38]:
sess.run(tf_tensor_2d)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [39]:
sess.run(tf_tensor_2d[3,3])

15.0

In [40]:
sess.run(tf_tensor_2d[1:3, 1:3])

array([[ 5.,  6.],
       [ 9., 10.]])

In [41]:
import tensorflow as tf
import numpy as np

# 3*3 행렬
matrix1 = np.array([(1,1,1), (1,1,1), (1,1,1)])
matrix2 = np.array([(2,2,2), (2,2,2), (2,2,2)])

# constant, 텐서 자료 구조로 변환
matrix1 = tf.constant(matrix1, dtype='int32')
matrix2 = tf.constant(matrix2, dtype='int32')

# 행렬곱과 행렬 합의 계산
matrix_mul = tf.matmul(matrix1, matrix2)
matrix_sum = tf.add(matrix1, matrix2)

# 행렬의 행렬식(determinant)
matrix3 = np.array([(2,7,2), (1,4,2), (9,0,2)], dtype='float32')
print('matrix3= {}'.format(matrix3))

matrix_dtm = tf.matrix_determinant(matrix3)
print('matrix_dtm = {}'.format(matrix_dtm))

matrix3= [[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]
matrix_dtm = Tensor("MatrixDeterminant:0", shape=(), dtype=float32)


In [42]:
# 세션을 열고 그래프 연산

with tf.Session() as sess:
  result1 = sess.run(matrix_mul)
  result2 = sess.run(matrix_sum)
  result3 = sess.run(matrix_dtm)
  
#연산결과 출력
print("matrix_mul = {}".format(result1))
print('matrix_sum = {}'.format(result2))
print('matrix_dtm = {}'.format(result3))

matrix_mul = [[6 6 6]
 [6 6 6]
 [6 6 6]]
matrix_sum = [[3 3 3]
 [3 3 3]
 [3 3 3]]
matrix_dtm = 55.99999237060547
